Update exception syntax to work with Python 3
This was the only syntactic issue causing an issue for Python 3.7.1.
When loaded it would fail with the following:

    $ python3 loadmovr.py load
      File "loadmovr.py", line 93
        except Exception, e: #@todo: catch the right exception
                        ^
    SyntaxError: invalid syntax